### ISSUE TITLE
questions about distance and rescaling

### ISSUE THREAD

**Issue by bzip2** [beringresearch/ivis#24]
Hi.

I'm trying out Ivis after reading your paper. Nice work and excellent documentation.

Could you clarify what you mean by "margin – The distance that **is enforced** between points by the triplet loss functions?" (Emphasis added.) This sounds like, "all distances are set to this value." From a quick read of your code, it sounds like this factor is added to all distances during loss calculations.

Also, your examples generally include a call to minmaxscaler. Is this required by Ivis, meaning that it makes assumptions about the scale of the distances between points, whether in the loss calculations or elsewhere?  

Thanks!

**Comment by idroz** [comment]
Hi - thanks, glad you find it useful!

## margin
Consider the triplet loss function that ivis is minimising:

![equation](https://latex.codecogs.com/gif.latex?%7BL%7D_%7Btri%7D%28%5Ctheta%20%29%3D%7B%5B%5Csum%20_%7Ba%2Cp%2Cn%7D%7BD%7D_%7Ba%2Cp%7D-min%28%7BD%7D_%7Ba%2Cn%7D%2C%7BD%7D_%7Bp%2Cn%7D%29&plus;m%5D%7D_%7B&plus;%7D)

``margin``  is represented as _m_, whilst _a_, _p_, and _n_ correspond to anchor, positive, and negative points respectively. _D_ is the Euclidean distance. This triplet constraint is said to be satisfied if the anchor point is closer to the positive point than to the negative point by a margin _m_.

In practice, we find that tuning ``margin`` doesn't have much effect on ivis embeddings. For example, check out [Supplementary Figure S4](https://static-content.springer.com/esm/art%3A10.1038%2Fs41598-019-45301-0/MediaObjects/41598_2019_45301_MOESM1_ESM.pdf) in the paper. We see that increasing ``margin`` to very high values (> 100) seems to produce exploding gradients. Therefore our recommendation is to stick to default settings. The only reason we haven't abstracted ``margin`` from the Ivis object constructor at this stage is because we'd still like to explore its effects on other data types e.g. word vectors.

## Scaling

ivis uses K-NN retrieval to build up a set of positive and negative triplets. This technique relies on approximating distances between points. If some features have very large values compared to others, they will dominate the triple retrieval, therefore we recommend scaling.

In most real-world cases, ``MinMaxScaler`` will be absolutely fine. Note that for really skewed data, log-transformation may be necessary prior to scaling. We're also looking into the effects of ``StandardScaler`` on embeddings, but so far ``MinMaxScaler`` produces "prettier" results! Once we collect enough data, we will updated the docs with appropriate recommendations.

**Comment by bzip2** [comment]
Thanks for the detailed answer, and for pointing me to the supplement. Both are very informative.
