### ISSUE TITLE
Windows compatibility?

### ISSUE THREAD

**Issue by paul-harambee** [beringresearch/ivis#25]
Really excited to compare Ivis to UMAP on a project I am currently working on.

The server I have access to is a Windows 10 machine, with a Python 3.7 Anaconda environment.

Following the install instructions and trying to run the MNIST example, I am seeing the following error: ```
TypeError: can't pickle annoy.Annoy objects```

**Comment by paul-harambee** [comment]
Full trace:

**Comment by paul-harambee** [comment]
Additionally, if I do not specify a full path to the annoy_index_path, I see the following:

```OSError: [Errno 22] Invalid argument```

**Comment by paul-harambee** [comment]
Trace:

```
Building KNN index
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-94d0c1d9d499> in <module>
     13 
     14 # Generate embeddings
---> 15 embeddings = model.fit_transform(X_scaled)

~\Anaconda3\lib\site-packages\ivis\ivis.py in fit_transform(self, X, Y, shuffle_mode)
    228         """
    229 
--> 230         self.fit(X, Y, shuffle_mode)
    231         return self.transform(X)
    232 

~\Anaconda3\lib\site-packages\ivis\ivis.py in fit(self, X, Y, shuffle_mode)
    207         """
    208 
--> 209         self._fit(X, Y, shuffle_mode)
    210         return self
    211 

~\Anaconda3\lib\site-packages\ivis\ivis.py in _fit(self, X, Y, shuffle_mode)
    124                 print('Building KNN index')
    125             build_annoy_index(X, self.annoy_index_path,
--> 126                               ntrees=self.ntrees, verbose=self.verbose)
    127 
    128         datagen = generator_from_index(X, Y,

~\Anaconda3\lib\site-packages\ivis\data\knn.py in build_annoy_index(X, path, ntrees, verbose)
     15 
     16     index = AnnoyIndex(X.shape[1])
---> 17     index.on_disk_build(path)
     18 
     19     if issparse(X):

OSError: [Errno 22] Invalid argument
```

**Comment by paul-harambee** [comment]
May be useful? https://github.com/spotify/annoy/issues/367

**Comment by idroz** [comment]
Hi - thanks for trying out ivis.

We haven't tested the package on a Windows machine, but judging from error traces, the issues may be around multicore retrieval of KNNs that require the Annoy index to be mmapped to memory.

With respect to ``annoy_index_path`` - ivis automatically assigns a path to the nearest neighbour index if one wasn't provided. I suspect here the issue may be the slight differences in how paths are interpreted on Windows vs Linux machines.

To get to the bottom of this, we'll need get a hold of a windows VM and reproduce these errors.

Meanwhile, you could try and test out ivis through a docker container.

**Comment by paul-harambee** [comment]
Thought as much. 

One other thing I've noticed.. If I do not pre-compute the index, it gets a bit further but then fails on something seemingly different:

```

**Comment by idroz** [comment]
Yea - that makes sense. With ``precompute=False`` ivis goes straight into training the network and retrieves NNs just for a training batch at training time - a feature that allows us to scale ivis to out-of-memory datasets.

Downloading a Windows VM now and will start testing.

Just to warn you - may take a week or two for any changes to be released into the master branch as we have tests that need to be passed and new tests for Windows will need to be written if an official support is to be implemented.

**Comment by paul-harambee** [comment]
No worries. Appreciate the speedy reply. Happy to be a guinea pig if needed. :)

**Comment by idroz** [comment]
Hi - I managed to reproduce the issue on a Windows machine and unfortunately it seems to be a lot more complicated than I originally thought.

The error is generated by a method that carries out multicore retrieval of nearest neighbours from an on-disk Annoy index. The index file (``annoy.index``) is mmaped across processes and workers then retrieve the neighbours.

Now, on Linux-y systems only the main process runs the whole module, while on Windows, all new processes run the entire module "from scratch". This means that on Linux-y systems, it isn't necessary to pickle objects whilst passing them around each fork, but it is necessary to pickle them on Windows...and Annoy index is not pickleable...

Because of this frustrating distinction, single thread neighbour retrieval will work absolutely fine on both Windows and Linux, but multithreading will fail. Only multi-threaded retrieval is implemented in ``ivis`` for speed.

It would be great if we could get some help wrangling python's multiprocessing module to play nicely with annoy index on Windows and we'll carry on working  on it. For the time being, I think you'd be better off running ivis inside a docker container.

**Comment by paul-harambee** [comment]
I have a few ideas on this. Will take a crack at it in the coming week.

**Comment by Szubie** [comment]
Hi, have pushed a branch with some changes made for Windows compatibility: https://github.com/beringresearch/ivis/tree/windows-annoy

The branch has been tested on Python 3.7.

When on Windows, on disk-building of the Annoy Index will be disabled as it doesn't seem to work currently (see https://github.com/spotify/annoy/issues/353). 

Do try out the new branch and let us know if you encounter any further issues.

**Comment by paul-harambee** [comment]
Brilliant. I have put some time aside to look at this tomorrow. Will provide feedback. :)

**Comment by paul-harambee** [comment]
I can confirm this is working my side. I've tested on a Python 3.7 and Python 3.6 environment. Both Windows 10.

I suppose this does mean there are memory limitations for a user to consider when running this on Windows for now. It may be useful to just have a note on this in the wiki. 

Thanks a lot.
