### ISSUE TITLE
Unstable result on dimensionality reduction

### ISSUE THREAD

**Issue by abdalimran** [beringresearch/ivis#31]
I'm trying Ivis for dimensionality reduction on Iris dataset. My code is as follows:
```
from ivis import Ivis
ivis_model = Ivis(embedding_dims=3, k=5, verbose=False, model='hinton')
ivis_data = ivis_model.fit_transform(data.drop(["species"], axis=1).values)
```
The problem is each of the time I run the above code chunk, I get different results. What can cause this unstability issue?

**Comment by idroz** [comment]
Hi there, thanks for trying out ivis!

There are several stochastic processes that form the basis of `ivis` functionality -  k-nearest neighbour retrieval using random projection trees and random initialisation of neural network weights.

`ivis` wasn't really designed to address dimensionality reduction in datasets with small number of observations (n<1000) e.g. iris. PCA or MDS are better suited to this task. `ivis` embeddings become stable with addition of more observations and increasing variance in the dataset. For example, see Supplementary Figure S2 of our recently-published paper on 'ivis' (https://static-content.springer.com/esm/art%3A10.1038%2Fs41598-019-45301-0/MediaObjects/41598_2019_45301_MOESM1_ESM.pdf).

Here's a quick visualisation of 10 `ivis` runs on a dataset with 5000 observations, which produces stable embeddings. Note that due to the stochastic properties I mentioned earlier, there will always be some rotation, but `ivis` will attempt to preserve inter-observation distances.
<img width="962" alt="Ivis-embeddings" src="https://user-images.githubusercontent.com/12413294/62012323-d8a0f900-b17c-11e9-98a7-94326b0265f5.png">

**Comment by abdalimran** [comment]
Understood. Thanks for the explanation.
