### ISSUE TITLE
Consider adding automated tests

### ISSUE THREAD

**Issue by SaskiaFreytag** [beringresearch/ivis#33]
Also part of the [JOSS-Review](https://github.com/openjournals/joss-reviews/issues/1596).

Please consider adding [automated tests](http://r-pkgs.had.co.nz/tests.html) for the R package.

**Comment by kevinrue** [comment]
It may be slightly more difficult to set up than "pure" R packages, but once your first R tests pass successfully on your local machine, I also recommend using [Travis CI](https://travis-ci.org) to run those tests automatically and display a [badge](https://docs.travis-ci.com/user/status-images/) in the README file to track and advertise the result of those tests.

**Comment by Szubie** [comment]
We have set up Travis CI to build the latest version of the code and run tests for both the Python and R packages automatically. We've also added a badge in the README displays the results - currently, all tests are passing.

**Comment by kevinrue** [comment]
Great work thanks!
With Travis CI in place, could you please add code coverage? 
Sorry to bump the goal post. I am genuinely trying to help. You probably know how code coverage can save you time down the road in terms of development and debugging.

This is fairly straightforward at this point.
Allow me to use one of my repositories as an example (https://github.com/csoneson/iSEE)

I may forget a detail or two, but it should be as easy as:

Adding the following to your [.travis.yml](https://github.com/beringresearch/ivis/blob/master/.travis.yml) 
```yaml
r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
```

Adding a `codecov.yml` file to your repository, here in an example:  https://github.com/csoneson/iSEE/blob/master/codecov.yml

To help you, you may want to use the CRAN [usethis](https://cran.r-project.org/web/packages/usethis/index.html) package, in particular the function `usethis::use_coverage()` to get template files rather than copy paste from the iSEE repository.

Thanks again for your responsiveness in this review process!

**Comment by idroz** [comment]
Thanks for the info! We added code coverage to [.travis.yml](https://github.com/beringresearch/ivis/blob/master/.travis.yml) and successfully tased sync with Codecov.io. Travis CI build is passing as well.

**Comment by kevinrue** [comment]
Great.
Here is the snippet to add the codecov badge to your README:

```
[![Codecov.io coverage status](https://codecov.io/github/beringresearch/ivis/coverage.svg?branch=master)](https://codecov.io/github/beringresearch/ivis)
```

[![Codecov.io coverage status](https://codecov.io/github/beringresearch/ivis/coverage.svg?branch=master)](https://codecov.io/github/beringresearch/ivis)

In the future, you can choose to either work on increase coverage where possible, or alternatively `covr` allows you to exclude certain parts of your code from the coverage testing. This should generally be reserved for parts of the code that _cannot_ be tested.
See https://cran.r-project.org/web/packages/covr/readme/README.html#exclusion-comments

**Comment by idroz** [comment]
Nice! There were several things that we couldn't test - namely zzz.R and install_ivis.R. It's good to know that these can be excluded.

I did try to simply load the ``.onLoad()`` function as a means of testing zzz.R but since reticulate seems to enforce `<<-` operation on imported python objects, was unable to do so without raising an error.
