### ISSUE TITLE
Default usage of 'annoy.index' is problematic.

### ISSUE THREAD

**Issue by ForrestCKoch** [beringresearch/ivis#54]
I am benchmarking this method on a cluster which uses a shared file system.  The problem is that the `Ivis` class creates a file, `annoy.index`, without checking whether it first exists.  This file is overwritten without giving any warning/error presumably causing issues for the previously existing program.

~~I see that this can be remedied by setting `annoy_index_path`; however, I this limitation is not obvious from the documentation and is likely to cause confusion.~~
Actually it appears this cannot be done.  This argument tells the program to load from this file, so there is no option to actually change the name of the index file ...

Edit:
Also, the `annoy.index` file is still created even if I set `build_index_on_disk=False`

**Comment by idroz** [comment]
Hi there - you can try to create an index first and then pass it to ivis. For example:

```python
from ivis import Ivis
from ivis.data.knn import build_annoy_index

from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler

data = load_iris()['data']
X = StandardScaler().fit_transform(data)

# Build the index here before initialising Ivis class
build_annoy_index(X, 'some_other_annoy_index_name.index')

ivis = Ivis(annoy_index_path='externall_annoy.index', k=15)
xy = ivis.fit_transform(X)
```

We'll have a look at ``build_index_on_disk`` option.

Thanks for flagging this!

**Comment by ForrestCKoch** [comment]
Thanks for the solution -- this will work well for me. I might suggest adding a note in your documentation, however, as it was not clear to me that I could not train the model on two different datasets simultaneously.  No warnings were thrown, and nothing crashed, so I might not have realized that my results were corrupted.

I haven't found the overhead of creating the knn-index to be too bad, so I will probably just use a temp file for this.

Regarding the `build_index_on_disk` issue, I should have given you some more information about my system:
- CentOS Linux release 7.4.1708
- Python version 3.6.6
- Ivis version 1.6.0
- Annoy version 1.16.2

Thanks for your help -- other than this it's been a very straightforward package to use.  I especially appreciate the scikit-learn style design!

**Comment by idroz** [comment]
Glad it works for you.

``build_index_on_disk``
This option allows ivis to build annoy index directly to disk rather than RAM (as such as not used as a flag to save or not to save the index to disk). This is especially useful for datasets that don't fit into RAM. In either case, an index file will be generated on disk. This was an initial design concept as it has several advantages:

- You can actually interrupt and restart model training. Ivis will carry on from the point where it was interrupted
- Building an index for very large files can take a long time (on some our datasets, as much as 24 hours). This was our own use case and hence the decision to save the index once and train from that
- Saved model is reproducible. Given that annoy uses random projection trees, results are stochastic.

I think you bring up an important point. Perhaps we could save an index as a temporary file, as that will potentially ensure its uniqueness. In either case, I've documented ``build_annoy_index`` method in library API (https://bering-ivis.readthedocs.io/en/latest/api.html#module-ivis.data.knn).
