### ISSUE TITLE
Under tensorflow 2.2.0 ivis fails to load a saved model

### ISSUE THREAD

**Issue by idroz** [beringresearch/ivis#71]
To reproduce:

1. `pip3 install tensorflow --upgrade`

```python
from sklearn.datasets import load_iris
from ivis import Ivis

X = load_iris()['data']
y = load_iris()['target']

# Supervised and unsupervised modes result in the same error
ivis = Ivis(k=5, batch_size=8).fit(X, y)
ivis.save_model('tmp.ivis')

model = Ivis()
model.load_model('tmp.ivis')
```

This results in `AttributeError: 'Model' object has no attribute '_make_predict_function'`

**Comment by Szubie** [comment]
Fixed in https://github.com/beringresearch/ivis/commit/35c8eb51a9b871b82c8d2691c88eb1e8dce0f962 by removing the call to the private API `_make_predict_function`, which is discouraged (https://github.com/keras-team/keras/pull/13116).

The line doesn't seem necessary when testing with any version of TensorFlow that can run ivis (from TensorFlow 1.13.1 upwards). Updated minimum TensorFlow version requirements in `requirements.txt` (https://github.com/beringresearch/ivis/commit/295bb545af16eea2b928b48ecb3ca311b6d382e0).
